/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package searchencrypted;

/**
 *
 * @author ibraheem
 */
import searchencrypted.DistanceMeasure;
import searchencrypted.HashFunction;
import java.io.Serializable;

/**
 * An interface representing a family of hash functions. A hash family has the
 * ability to generate a new member of the family, and can combine hashes
 * generated by a family of hash functions.
 * 
 * @author Joren Six
 * 
 */
public interface HashFamily extends Serializable {

	/**
	 * Create a new hash function of this family.
	 * 
	 * @return A new hash function of this family.
	 */
	HashFunction createHashFunction();

	/**
	 * Combine a number of hashes generated by members of this hash function
	 * family.
	 * 
	 * @param hashes
	 *            The raw hashes that need to be combined.
	 * @return An integer representing a combination of the hashes. Normally,
	 *         unique hash values result in a unique, deterministic combined
	 *         hash value.
	 */
	Integer combine(int[] hashes);
	
	/**
	 * Create a new distance measure.
	 * 
	 * @return The distance measure used to sort neighbourhood candidates.
	 */
	DistanceMeasure createDistanceMeasure();

}
